### ISSUE TITLE
tr808: add the "other" sounds

### ISSUE THREAD

**Issue by reduzent** [reduzent/netpd-instruments#21]
Before git was common, I once had quite a lot of the TR-808 sounds synthesized in Pd. However, due to some stupid mistake I lost them all but kick and clap. Would be nice to have them back.

**Comment by fferri** [comment]
I remember that. Unfortunately I lost that stuff too.

Found these patches around:

808 pd patches:
https://github.com/danomatika/rc-patches/tree/master/rc

808 pd patches:
https://github.com/damian0815/dlib

cymbal, rimshot and clap can be found here:
https://forum.pdpatchrepo.info/topic/9511/looking-for-good-drum-synths/10

More drum synthesis pd patches here (mymembrane~):
https://github.com/MikeMorenoDSP/pd-mkmr/tree/master/instruments

And also these videos:

TR 808 Snare in Pure Data Vanilla:
https://www.youtube.com/watch?v=Irguro-mssc

Pure Data - TR-808 style snare drum synthesis: (sounds more like a TR-909 snare IMHO)
https://www.youtube.com/watch?v=mfoh0ucl238

Pure Data - 808 style hi-hat synthesis:
https://www.youtube.com/watch?v=ENMlT1Ar5L0

Pure Data - TR-808 style cowbell synthesis:
https://www.youtube.com/watch?v=hS1KTGjn9CY

Pure Data - TR-909 style clap synthesis:
https://www.youtube.com/watch?v=lBPWBZRowzc

Pure Data - TR-909 style kick and tom synthesis:
https://www.youtube.com/watch?v=4kc4MD1lTEo

**Comment by reduzent** [comment]
wow, you did some research. Very cool!

I think I'll incorporate some 808 stuff from your links above into tr808. Good stuff there!

**Comment by fferri** [comment]
Looking forward to it!  :-)

**Comment by reduzent** [comment]
tr808 now has:
  * bassdrum
  * snare
  * clap
  * open and closed hihat
  * bell
  * cymbal
  * rimshot
