### ISSUE TITLE
qseq3 misses beats

### ISSUE THREAD

**Issue by nofoto** [reduzent/netpd-instruments#31]
Here is a strange little bug - if I launch 'unpatch' and create a simple setup with drum-delta or something and qseq3 and give it a polyrhythm of 3/4 with a 12:3 layout, qseq3 will mute every third cell (bom,bom,pause,bom,bom,pause) but  as soon as I change the tempo from the default 120 it fixes itself and plays everything properly. I can move the tempo back to 120 and it works ok.
On MacOSX 10.13.6 Pd 0.51-4 netpd 2.3.0

**Comment by reduzent** [comment]
OK, I can reproduce it. This is somewhat similar to #36. I can trigger the behavior you describe by hitting `save` in unpatch.

**Comment by reduzent** [comment]
The fix is also similar to the one used for #36. When stopping [rh_metro] each time before restarting it, the problem doesn't occur. The problem before was that when the next sync tick arrived before it was stopped, it would not output that bang.
