### ISSUE TITLE
lilacid piano roll array glitch

### ISSUE THREAD

**Issue by nofoto** [reduzent/netpd-instruments#32]
In lilacid one note at the bottom of the unstep piano roll (Fsharp?) will not sound and gives this error message:
tabosc4~: NBLSQUARE119: no such array

**Comment by reduzent** [comment]
Turns out it was a typical "off-by-one" error. However, the problem is not in lilacid, nor in nblsquare~  or nblsquare_tables, but in  [netpd-nb-until]! I fixed it there, but it means the fix is in netpd and not in netpd-instruments. Related issue: https://github.com/reduzent/netpd/issues/22

**Comment by reduzent** [comment]
Fixed in https://github.com/reduzent/netpd
